### ISSUE TITLE
Can't compile for iOS

### ISSUE THREAD

**Issue by ZenCocoon** [BookingSync/smily-mobile-app#1]
![Image 2022-02-02 at 3 14 18 PM](https://user-images.githubusercontent.com/10502/152171347-2ee9c37f-fc37-4b1d-98ef-740265886689.jpg)

![Image 2022-02-02 at 3 19 06 PM](https://user-images.githubusercontent.com/10502/152171463-a7549eae-6569-4538-801f-807a257c2cfb.jpg)

**Comment by EroMCakes** [comment]
Turns out this issue is caused by generating build for multiple platforms. To solve it you'll need to follow bellow steps: 

1. as a security first run this command to ensure flutter and all dependencies are correctly installed: flutter doctor
2.  navigate on your terminal to the project root
3. run following command : flutter clean && flutter pub get && cd ios/ && pod install

This should solve the issue.

**Comment by ZenCocoon** [comment]
Awesome. now it works 🎉
